/* ╔═══════════════════════════════════════════════════════════════╗
   ║  POETRY VOICE · DATA                                          ║
   ║  Poemas em domínio público (originais ou substituições        ║
   ║  por autores canónicos de domínio público).                   ║
   ╚═══════════════════════════════════════════════════════════════╝ */

// UI strings — interface in Portuguese (utilizador nativo)
const UI = {
  appTitle: "Poetry Voice",
  appSubtitle: "Scriptorium de leitura e escuta",

  // Nav
  langLabel: "Idioma do poema",
  flagEN: "✦ ENGLISH",
  flagPT: "✦ PORTUGUÊS",
  flagES: "✦ ESPAÑOL",

  // Library
  libraryTitle: "Códice de Poemas",
  librarySubtitle: "Escolhei uma peça para escutar, sombrear ou memorizar",
  poemsCount: "peças no códice",
  authorAll: "Todos os autores",

  // Card
  read: "Ler",
  practice: "Praticar",
  favorite: "Favoritar",
  unfavorite: "Desfavoritar",
  sessions: "leituras",

  // Poem screen
  back: "← Códice",
  about: "Sobre o poema",
  pronunciation: "Pronúncia das palavras difíceis",
  glossaryHint: "Toque qualquer palavra para tradução e definição",
  progress: "Progresso",

  // Modes
  modeListening: "Escutar",
  modeShadow: "Sombrear",
  modeKaraoke: "Karaoke",
  modeMemo: "Memorizar",
  modeRecord: "Gravar leitura",

  // Mode descriptions
  descListening: "Ouvi o poema lido em voz alta. Acompanhai palavra por palavra.",
  descShadow: "Repeti cada verso após a leitura. Pausa configurável.",
  descKaraoke: "Leitura lenta para acompanhar em conjunto.",
  descMemo: "As últimas palavras de cada verso ocultas. Completai de memória.",
  descRecord: "Falai o poema; mediremos a vossa precisão.",

  // Controls
  play: "Reproduzir",
  pause: "Pausa",
  stop: "Cessar",
  repeat: "Repetir estrofe",
  next: "Próximo verso",
  voice: "Voz",
  voiceMale: "Masculina",
  voiceFemale: "Feminina",
  speed: "Velocidade",
  speedSlow: "Lenta",
  speedNormal: "Normal",
  speedFast: "Rápida",
  pauseBetween: "Pausa entre versos",
  hideWords: "Palavras ocultas no verso",

  // Recording
  startRecord: "Iniciar gravação",
  stopRecord: "Parar gravação",
  listening: "A ouvir…",
  noSpeechApi: "O vosso navegador não suporta reconhecimento de fala. Tentai o Chrome ou Edge.",
  recognized: "Texto reconhecido",
  accuracy: "Acurácia",
  noVoiceWarning: "Não foi encontrada voz nativa para este idioma no vosso sistema. Sugerimos instalar vozes nas preferências do dispositivo (Configurações → Acessibilidade → Conteúdo Falado).",
  voiceUsed: "Voz em uso",

  // Misc
  light: "luz",
  dark: "sombra",
  empty: "—",
  loading: "Carregando vozes do scriptorium…",
  begin: "Iniciar leitura",
  reveal: "Revelar",
  finished: "Leitura concluída.",
  yourReading: "Vossa leitura",

  // Custom poems
  addPoem: "Adicionar poema",
  myCodex: "Meu códice",
  newPoem: "Novo poema",
  editPoem: "Editar peça",
  fieldTitle: "Título",
  fieldAuthor: "Autor (ou anônimo)",
  fieldYear: "Ano (opcional)",
  fieldLang: "Idioma",
  fieldSubtitle: "Verso de abertura ou subtítulo (opcional)",
  fieldText: "Texto do poema",
  fieldTextHelp: "Separe estrofes com uma linha em branco. Cada linha é um verso.",
  save: "Salvar",
  cancel: "Cancelar",
  delete: "Excluir",
  confirmDelete: "Excluir esta peça do códice?",
  custom: "Próprio",
  validationTitle: "Dai um título à peça.",
  validationText: "O texto não pode estar vazio.",
};

// Author era badges
const ERAS = {
  renaissance: "Renascença",
  baroque: "Barroco",
  romantic: "Romantismo",
  modernist: "Modernismo",
  goldenAge: "Século de Ouro",
  parnasian: "Parnasianismo",
  generation27: "Geração de 27",
  generation98: "Geração de 98",
  victorian: "Vitoriano",
};

/* ────────────────────────────────────────────────────────────
   POEMS — 4 por idioma, todos em domínio público
   ──────────────────────────────────────────────────────────── */
const POEMS = [

  /* ═══════════ ENGLISH ═══════════ */
  {
    id: "en-sonnet18",
    lang: "en",
    locale: "en-GB",
    author: "William Shakespeare",
    year: "1609",
    era: "renaissance",
    title: "Sonnet XVIII",
    subtitle: "Shall I compare thee to a summer's day?",
    blurb: "Um soneto sobre a permanência da beleza através do verso. Pentâmetro iâmbico clássico.",
    stanzas: [
      [
        "Shall I compare thee to a summer's day?",
        "Thou art more lovely and more temperate:",
        "Rough winds do shake the darling buds of May,",
        "And summer's lease hath all too short a date:",
      ],
      [
        "Sometime too hot the eye of heaven shines,",
        "And often is his gold complexion dimm'd;",
        "And every fair from fair sometime declines,",
        "By chance or nature's changing course untrimm'd;",
      ],
      [
        "But thy eternal summer shall not fade,",
        "Nor lose possession of that fair thou ow'st;",
        "Nor shall Death brag thou wander'st in his shade,",
        "When in eternal lines to time thou grow'st;",
      ],
      [
        "So long as men can breathe or eyes can see,",
        "So long lives this, and this gives life to thee.",
      ],
    ],
    pronunciation: [
      { word: "thee", hint: "thi", ipa: "ðiː" },
      { word: "thou", hint: "thau", ipa: "ðaʊ" },
      { word: "temperate", hint: "TEM-pe-rit", ipa: "ˈtɛmpərət" },
      { word: "darling", hint: "DAR-ling", ipa: "ˈdɑːlɪŋ" },
      { word: "complexion", hint: "kom-PLEK-shen", ipa: "kəmˈplɛkʃən" },
      { word: "wander'st", hint: "WON-derst", ipa: "ˈwɒndərst" },
      { word: "eternal", hint: "i-TER-nul", ipa: "ɪˈtɜːnəl" },
      { word: "breathe", hint: "briidh", ipa: "briːð" },
    ],
    glossary: {
      "thee": { def: "Forma arcaica de 'you' (objeto). Pronome de segunda pessoa.", t: { pt: "te / a ti", es: "te / a ti" } },
      "thou": { def: "Forma arcaica de 'you' (sujeito). Familiar e poético.", t: { pt: "tu", es: "tú" } },
      "temperate": { def: "Suave, moderado em temperamento ou clima.", t: { pt: "temperado, sereno", es: "templado, sereno" } },
      "rough": { def: "Áspero, violento, agitado.", t: { pt: "áspero, rude", es: "áspero, rudo" } },
      "lease": { def: "Período concedido; arrendamento.", t: { pt: "prazo, arrendamento", es: "plazo, arriendo" } },
      "fade": { def: "Desvanecer, perder cor ou força.", t: { pt: "desvanecer", es: "desvanecerse" } },
      "shade": { def: "Sombra; reino dos mortos na poesia clássica.", t: { pt: "sombra", es: "sombra" } },
      "brag": { def: "Gabar-se, vangloriar-se.", t: { pt: "gabar-se", es: "jactarse" } },
      "summer": { def: "Estação quente do ano.", t: { pt: "verão", es: "verano" } },
      "eternal": { def: "Sem fim no tempo.", t: { pt: "eterno", es: "eterno" } },
    },
  },

  {
    id: "en-road",
    lang: "en",
    locale: "en-US",
    author: "Robert Frost",
    year: "1916",
    era: "modernist",
    title: "The Road Not Taken",
    subtitle: "Two roads diverged in a yellow wood…",
    blurb: "A escolha, o caminho, e o que se conta depois. Métrica iâmbica de quatro acentos.",
    stanzas: [
      [
        "Two roads diverged in a yellow wood,",
        "And sorry I could not travel both",
        "And be one traveler, long I stood",
        "And looked down one as far as I could",
        "To where it bent in the undergrowth;",
      ],
      [
        "Then took the other, as just as fair,",
        "And having perhaps the better claim,",
        "Because it was grassy and wanted wear;",
        "Though as for that the passing there",
        "Had worn them really about the same,",
      ],
      [
        "And both that morning equally lay",
        "In leaves no step had trodden black.",
        "Oh, I kept the first for another day!",
        "Yet knowing how way leads on to way,",
        "I doubted if I should ever come back.",
      ],
      [
        "I shall be telling this with a sigh",
        "Somewhere ages and ages hence:",
        "Two roads diverged in a wood, and I—",
        "I took the one less traveled by,",
        "And that has made all the difference.",
      ],
    ],
    pronunciation: [
      { word: "diverged", hint: "dai-VERJD", ipa: "daɪˈvɜːdʒd" },
      { word: "yellow", hint: "YEL-oh", ipa: "ˈjɛloʊ" },
      { word: "traveler", hint: "TRAV-el-er", ipa: "ˈtrævələr" },
      { word: "undergrowth", hint: "UN-der-groth", ipa: "ˈʌndərɡroʊθ" },
      { word: "perhaps", hint: "per-HAPS", ipa: "pərˈhæps" },
      { word: "trodden", hint: "TROD-en", ipa: "ˈtrɒdən" },
      { word: "though", hint: "thoh", ipa: "ðoʊ" },
      { word: "doubted", hint: "DOW-ted", ipa: "ˈdaʊtɪd" },
      { word: "sigh", hint: "sai", ipa: "saɪ" },
    ],
    glossary: {
      "diverged": { def: "Bifurcar-se, separar-se em direções distintas.", t: { pt: "bifurcaram-se", es: "se bifurcaron" } },
      "yellow": { def: "Cor do outono; tons de amarelo nas folhas.", t: { pt: "amarelo", es: "amarillo" } },
      "wood": { def: "Bosque, floresta pequena.", t: { pt: "bosque", es: "bosque" } },
      "sorry": { def: "Pesaroso, com pena.", t: { pt: "pesaroso", es: "apenado" } },
      "traveler": { def: "Aquele que viaja.", t: { pt: "viajante", es: "viajero" } },
      "claim": { def: "Reivindicação, direito alegado.", t: { pt: "reivindicação", es: "reclamo" } },
      "grassy": { def: "Coberto de relva.", t: { pt: "relvado", es: "cubierto de hierba" } },
      "trodden": { def: "Pisado, marcado por passos. Particípio de 'tread'.", t: { pt: "pisado", es: "pisado" } },
      "sigh": { def: "Suspiro, expiração audível.", t: { pt: "suspiro", es: "suspiro" } },
      "hence": { def: "A partir daqui, daqui por diante.", t: { pt: "daqui", es: "de aquí" } },
    },
  },

  {
    id: "en-hope",
    lang: "en",
    locale: "en-US",
    author: "Emily Dickinson",
    year: "1891",
    era: "victorian",
    title: '"Hope" is the thing with feathers',
    subtitle: "A esperança como ave que canta sem parar.",
    blurb: "Travessões característicos, métrica de hino. Imagem da esperança como pássaro.",
    stanzas: [
      [
        '"Hope" is the thing with feathers—',
        "That perches in the soul—",
        "And sings the tune without the words—",
        "And never stops—at all—",
      ],
      [
        "And sweetest—in the Gale—is heard—",
        "And sore must be the storm—",
        "That could abash the little Bird",
        "That kept so many warm—",
      ],
      [
        "I've heard it in the chillest land—",
        "And on the strangest Sea—",
        "Yet, never, in Extremity,",
        "It asked a crumb—of Me.",
      ],
    ],
    pronunciation: [
      { word: "feathers", hint: "FETH-erz", ipa: "ˈfɛðərz" },
      { word: "perches", hint: "PER-chiz", ipa: "ˈpɜːtʃɪz" },
      { word: "tune", hint: "tyoon", ipa: "tjuːn" },
      { word: "gale", hint: "geyl", ipa: "ɡeɪl" },
      { word: "sore", hint: "sor", ipa: "sɔːr" },
      { word: "abash", hint: "uh-BASH", ipa: "əˈbæʃ" },
      { word: "chillest", hint: "CHIL-ist", ipa: "ˈtʃɪlɪst" },
      { word: "extremity", hint: "ek-STREM-i-ti", ipa: "ɪkˈstrɛmɪti" },
      { word: "crumb", hint: "krum", ipa: "krʌm" },
    ],
    glossary: {
      "feathers": { def: "Plumas de aves.", t: { pt: "penas", es: "plumas" } },
      "perches": { def: "Pousa, repousa em um poleiro.", t: { pt: "pousa", es: "se posa" } },
      "soul": { def: "Alma, espírito interior.", t: { pt: "alma", es: "alma" } },
      "tune": { def: "Melodia, canto musical.", t: { pt: "melodia", es: "melodía" } },
      "gale": { def: "Ventania, tempestade.", t: { pt: "vendaval", es: "vendaval" } },
      "abash": { def: "Envergonhar, intimidar.", t: { pt: "envergonhar", es: "avergonzar" } },
      "warm": { def: "Quente, aconchegado.", t: { pt: "aquecido", es: "cálido" } },
      "chillest": { def: "O mais frio. Superlativo de 'chill'.", t: { pt: "mais gélido", es: "más helado" } },
      "extremity": { def: "Situação extrema, ponto crítico.", t: { pt: "extremidade", es: "extremidad" } },
      "crumb": { def: "Migalha de pão; pouca coisa.", t: { pt: "migalha", es: "miga" } },
    },
  },

  {
    id: "en-dream",
    lang: "en",
    locale: "en-US",
    author: "Edgar Allan Poe",
    year: "1849",
    era: "romantic",
    title: "A Dream Within a Dream",
    subtitle: "Tudo o que vemos ou parecemos é apenas um sonho dentro de um sonho.",
    blurb: "Meditação sobre o tempo, a perda e a natureza do real. Métrica anapéstica viva.",
    stanzas: [
      [
        "Take this kiss upon the brow!",
        "And, in parting from you now,",
        "Thus much let me avow—",
        "You are not wrong, who deem",
        "That my days have been a dream;",
        "Yet if hope has flown away",
        "In a night, or in a day,",
        "In a vision, or in none,",
        "Is it therefore the less gone?",
        "All that we see or seem",
        "Is but a dream within a dream.",
      ],
      [
        "I stand amid the roar",
        "Of a surf-tormented shore,",
        "And I hold within my hand",
        "Grains of the golden sand—",
        "How few! yet how they creep",
        "Through my fingers to the deep,",
        "While I weep—while I weep!",
        "O God! Can I not grasp",
        "Them with a tighter clasp?",
        "O God! can I not save",
        "One from the pitiless wave?",
        "Is all that we see or seem",
        "But a dream within a dream?",
      ],
    ],
    pronunciation: [
      { word: "brow", hint: "brau", ipa: "braʊ" },
      { word: "avow", hint: "uh-VAU", ipa: "əˈvaʊ" },
      { word: "deem", hint: "diim", ipa: "diːm" },
      { word: "amid", hint: "uh-MID", ipa: "əˈmɪd" },
      { word: "surf-tormented", hint: "serf tor-MENT-ed", ipa: "sɜːf tɔːrˈmɛntɪd" },
      { word: "weep", hint: "wiip", ipa: "wiːp" },
      { word: "grasp", hint: "grasp", ipa: "ɡræsp" },
      { word: "pitiless", hint: "PIT-i-les", ipa: "ˈpɪtɪləs" },
    ],
    glossary: {
      "brow": { def: "Testa, fronte.", t: { pt: "fronte, testa", es: "frente" } },
      "avow": { def: "Declarar abertamente, confessar.", t: { pt: "confessar", es: "confesar" } },
      "deem": { def: "Considerar, julgar.", t: { pt: "considerar", es: "considerar" } },
      "vision": { def: "Visão, sonho desperto.", t: { pt: "visão", es: "visión" } },
      "amid": { def: "No meio de.", t: { pt: "no meio de", es: "en medio de" } },
      "roar": { def: "Rugido, estrondo.", t: { pt: "rugido", es: "rugido" } },
      "shore": { def: "Praia, margem do mar.", t: { pt: "praia", es: "orilla" } },
      "creep": { def: "Escapar-se lentamente; rastejar.", t: { pt: "escorrer", es: "deslizarse" } },
      "weep": { def: "Chorar.", t: { pt: "chorar", es: "llorar" } },
      "pitiless": { def: "Sem piedade.", t: { pt: "impiedoso", es: "despiadado" } },
    },
  },

  /* ═══════════ PORTUGUÊS ═══════════ */
  {
    id: "pt-mar",
    lang: "pt",
    locale: "pt-PT",
    author: "Fernando Pessoa",
    year: "1934",
    era: "modernist",
    title: "Mar Português",
    subtitle: "Ó mar salgado, quanto do teu sal são lágrimas de Portugal!",
    blurb: "Da 'Mensagem'. Heterônimo: ortônimo. A epopeia marítima em versos íntimos.",
    stanzas: [
      [
        "Ó mar salgado, quanto do teu sal",
        "São lágrimas de Portugal!",
        "Por te cruzarmos, quantas mães choraram,",
        "Quantos filhos em vão rezaram!",
        "Quantas noivas ficaram por casar",
        "Para que fosses nosso, ó mar!",
      ],
      [
        "Valeu a pena? Tudo vale a pena",
        "Se a alma não é pequena.",
        "Quem quer passar além do Bojador",
        "Tem que passar além da dor.",
        "Deus ao mar o perigo e o abismo deu,",
        "Mas nele é que espelhou o céu.",
      ],
    ],
    pronunciation: [
      { word: "salgado", hint: "sau-GA-du", ipa: "sɐɫˈɡadu" },
      { word: "lágrimas", hint: "LÁ-gri-mas", ipa: "ˈlaɡɾimɐʃ" },
      { word: "cruzarmos", hint: "kru-ZAR-mus", ipa: "kɾuˈzaɾmuʃ" },
      { word: "noivas", hint: "NOI-vas", ipa: "ˈnojvɐʃ" },
      { word: "Bojador", hint: "bo-ja-DOR", ipa: "buʒɐˈdoɾ" },
      { word: "abismo", hint: "a-BIZ-mu", ipa: "ɐˈbiʒmu" },
      { word: "espelhou", hint: "es-pe-LHOU", ipa: "iʃpɨˈʎow" },
      { word: "céu", hint: "SÉU", ipa: "ˈsɛw" },
    ],
    glossary: {
      "salgado": { def: "Que contém sal; aquilo que é do mar.", t: { en: "salty, salted", es: "salado" } },
      "lágrimas": { def: "Gotas de pranto.", t: { en: "tears", es: "lágrimas" } },
      "cruzarmos": { def: "Atravessarmos, conjugação 1ª pl. fut. conj.", t: { en: "for us to cross", es: "que cruzáramos" } },
      "rezaram": { def: "Oraram; pret. perf. 3ª pl. de 'rezar'.", t: { en: "prayed", es: "rezaron" } },
      "noivas": { def: "Mulheres prometidas em casamento.", t: { en: "brides", es: "novias" } },
      "alma": { def: "Espírito, princípio vital.", t: { en: "soul", es: "alma" } },
      "Bojador": { def: "Cabo Bojador, marco mítico da expansão marítima portuguesa.", t: { en: "Cape Bojador", es: "Cabo Bojador" } },
      "perigo": { def: "Risco grave de dano.", t: { en: "danger", es: "peligro" } },
      "abismo": { def: "Profundeza vertiginosa.", t: { en: "abyss", es: "abismo" } },
      "céu": { def: "Firmamento; morada divina.", t: { en: "sky, heaven", es: "cielo" } },
    },
  },

  {
    id: "pt-lusiadas",
    lang: "pt",
    locale: "pt-PT",
    author: "Luís de Camões",
    year: "1572",
    era: "renaissance",
    title: "Os Lusíadas · Canto I (excerto)",
    subtitle: "As armas e os barões assinalados…",
    blurb: "Oitava rima clássica. Abertura da epopeia. Métrica decassílaba, ritmo grave.",
    stanzas: [
      [
        "As armas e os barões assinalados",
        "Que, da Ocidental praia Lusitana,",
        "Por mares nunca de antes navegados",
        "Passaram ainda além da Taprobana,",
        "Em perigos e guerras esforçados",
        "Mais do que prometia a força humana,",
        "E entre gente remota edificaram",
        "Novo Reino, que tanto sublimaram;",
      ],
      [
        "E também as memórias gloriosas",
        "Daqueles Reis que foram dilatando",
        "A Fé, o Império, e as terras viciosas",
        "De África e de Ásia andaram devastando;",
        "E aqueles que por obras valerosas",
        "Se vão da lei da Morte libertando:",
        "Cantando espalharei por toda parte,",
        "Se a tanto me ajudar o engenho e arte.",
      ],
    ],
    pronunciation: [
      { word: "barões", hint: "ba-RÕES", ipa: "bɐˈɾõjʃ" },
      { word: "assinalados", hint: "a-si-na-LA-dus", ipa: "ɐsinɐˈladuʃ" },
      { word: "Ocidental", hint: "o-si-den-TAL", ipa: "ɔsidẽˈtaɫ" },
      { word: "Lusitana", hint: "lu-zi-TA-na", ipa: "luziˈtɐnɐ" },
      { word: "Taprobana", hint: "ta-pro-BA-na", ipa: "tɐpɾuˈβɐnɐ" },
      { word: "remota", hint: "re-MÓ-ta", ipa: "ʁɨˈmɔtɐ" },
      { word: "edificaram", hint: "e-di-fi-CA-ram", ipa: "ɨdifiˈkaɾɐ̃w" },
      { word: "sublimaram", hint: "su-bli-MA-ram", ipa: "sublimaˈɾɐ̃w" },
    ],
    glossary: {
      "barões": { def: "Homens nobres; varões de armas.", t: { en: "barons, noble men", es: "varones, nobles" } },
      "assinalados": { def: "Notáveis, distintos pelas suas feitos.", t: { en: "distinguished", es: "señalados" } },
      "Lusitana": { def: "Relativo à Lusitânia; portuguesa.", t: { en: "Lusitanian (Portuguese)", es: "lusitana" } },
      "Taprobana": { def: "Antigo nome do Sri Lanka, fim do mundo conhecido.", t: { en: "Taprobane (Sri Lanka)", es: "Taprobana" } },
      "esforçados": { def: "Corajosos, valentes.", t: { en: "brave, valiant", es: "esforzados" } },
      "remota": { def: "Distante, longínqua.", t: { en: "remote", es: "remota" } },
      "edificaram": { def: "Construíram, fundaram.", t: { en: "built, founded", es: "edificaron" } },
      "sublimaram": { def: "Elevaram a alta dignidade.", t: { en: "elevated, exalted", es: "sublimaron" } },
      "dilatando": { def: "Expandindo, alargando.", t: { en: "expanding", es: "dilatando" } },
      "engenho": { def: "Talento, capacidade inventiva.", t: { en: "wit, ingenuity", es: "ingenio" } },
    },
  },

  {
    id: "pt-bilac",
    lang: "pt",
    locale: "pt-BR",
    author: "Olavo Bilac",
    year: "1919",
    era: "parnasian",
    title: "Língua Portuguesa",
    subtitle: "Última flor do Lácio, inculta e bela…",
    blurb: "Soneto parnasiano em louvor à própria língua. Perfeito para treinar pronúncia brasileira.",
    stanzas: [
      [
        "Última flor do Lácio, inculta e bela,",
        "És, a um tempo, esplendor e sepultura:",
        "Ouro nativo, que na ganga impura",
        "A bruta mina entre os cascalhos vela…",
      ],
      [
        "Amo-te assim, desconhecida e obscura,",
        "Tuba de alto clangor, lira singela,",
        "Que tens o trom e o silvo da procela",
        "E o arrolo da saudade e da ternura!",
      ],
      [
        "Amo o teu viço agreste e o teu aroma",
        "De virgens selvas e de oceano largo!",
        "Amo-te, ó rude e doloroso idioma,",
      ],
      [
        "Em que da voz materna ouvi: \"meu filho!\",",
        "E em que Camões chorou, no exílio amargo,",
        "O gênio sem ventura e o amor sem brilho!",
      ],
    ],
    pronunciation: [
      { word: "Lácio", hint: "LÁ-ci-u", ipa: "ˈlasju" },
      { word: "inculta", hint: "in-CUL-ta", ipa: "ĩˈkuwtɐ" },
      { word: "esplendor", hint: "es-plen-DOR", ipa: "isplẽˈdoʁ" },
      { word: "ganga", hint: "GAN-ga", ipa: "ˈɡɐ̃ɡɐ" },
      { word: "cascalhos", hint: "cas-CA-lhus", ipa: "kasˈkaʎus" },
      { word: "clangor", hint: "clan-GOR", ipa: "klɐ̃ˈɡoʁ" },
      { word: "procela", hint: "pro-CÉ-la", ipa: "pɾoˈsɛlɐ" },
      { word: "arrolo", hint: "a-RRO-lu", ipa: "aˈʁolu" },
      { word: "saudade", hint: "sau-DA-de", ipa: "sawˈdadʒi" },
    ],
    glossary: {
      "Lácio": { def: "Região da Itália onde nasceu o latim, mãe das línguas românicas.", t: { en: "Latium", es: "Lacio" } },
      "inculta": { def: "Não cultivada; aqui, em sentido positivo (selvagem, livre).", t: { en: "uncultivated, wild", es: "inculta" } },
      "sepultura": { def: "Túmulo; aquilo que encerra.", t: { en: "grave, tomb", es: "sepultura" } },
      "ganga": { def: "Mineral sem valor que envolve o minério precioso.", t: { en: "gangue (rock matrix)", es: "ganga" } },
      "cascalhos": { def: "Pedregulhos, fragmentos de rocha.", t: { en: "gravel", es: "cascajos" } },
      "clangor": { def: "Som metálico e estrondoso, como de trombeta.", t: { en: "clangor", es: "clangor" } },
      "lira": { def: "Instrumento de cordas; metáfora de poesia lírica.", t: { en: "lyre", es: "lira" } },
      "procela": { def: "Tempestade violenta no mar.", t: { en: "tempest, storm", es: "procela" } },
      "saudade": { def: "Sentimento nostálgico de ausência. Palavra emblemática do português.", t: { en: "saudade (longing)", es: "añoranza" } },
      "ventura": { def: "Sorte, felicidade; fortuna favorável.", t: { en: "good fortune", es: "ventura" } },
    },
  },

  {
    id: "pt-florbela",
    lang: "pt",
    locale: "pt-PT",
    author: "Florbela Espanca",
    year: "1930",
    era: "modernist",
    title: "Ser Poeta",
    subtitle: "É ser mais alto, é ser maior do que os Homens!",
    blurb: "Soneto sobre a vocação poética como exaltação e martírio. Versos decassílabos.",
    stanzas: [
      [
        "Ser Poeta é ser mais alto, é ser maior",
        "Do que os Homens! Morder como quem beija!",
        "É ser mendigo e dar como quem seja",
        "Rei do Reino de Aquém e de Além Dor!",
      ],
      [
        "É ter de mil desejos o esplendor",
        "E não saber sequer que se deseja!",
        "É ter cá dentro um astro que flameja,",
        "É ter garras e asas de condor!",
      ],
      [
        "É ter fome, é ter sede de Infinito!",
        "Por elmo, as manhãs de oiro e de cetim…",
        "É condensar o mundo num só grito!",
      ],
      [
        "E é amar-te, assim, perdidamente…",
        "É seres alma e sangue e vida em mim",
        "E dizê-lo cantando a toda a gente!",
      ],
    ],
    pronunciation: [
      { word: "poeta", hint: "po-É-ta", ipa: "puˈɛtɐ" },
      { word: "mendigo", hint: "men-DI-gu", ipa: "mẽˈdiɡu" },
      { word: "Aquém", hint: "a-QUÉM", ipa: "ɐˈkɐ̃j" },
      { word: "esplendor", hint: "es-plen-DOR", ipa: "ʃplẽˈdoɾ" },
      { word: "flameja", hint: "fla-ME-ja", ipa: "flɐˈmɐʒɐ" },
      { word: "condor", hint: "con-DOR", ipa: "kõˈdoɾ" },
      { word: "Infinito", hint: "in-fi-NI-tu", ipa: "ĩfiˈnitu" },
      { word: "elmo", hint: "EL-mu", ipa: "ˈɛɫmu" },
      { word: "cetim", hint: "se-TIM", ipa: "sɨˈtĩ" },
    ],
    glossary: {
      "Poeta": { def: "Aquele que compõe versos; criador em palavras.", t: { en: "poet", es: "poeta" } },
      "Morder": { def: "Apertar com os dentes; aqui, intensidade de afeto.", t: { en: "to bite", es: "morder" } },
      "mendigo": { def: "Aquele que pede esmola.", t: { en: "beggar", es: "mendigo" } },
      "Aquém": { def: "Deste lado; antônimo de 'Além'.", t: { en: "this side of", es: "más acá" } },
      "esplendor": { def: "Brilho intenso, magnificência.", t: { en: "splendor", es: "esplendor" } },
      "flameja": { def: "Arde em chamas, resplandece.", t: { en: "flames, blazes", es: "llamea" } },
      "garras": { def: "Unhas curvas e fortes de aves de rapina.", t: { en: "talons, claws", es: "garras" } },
      "elmo": { def: "Capacete medieval que cobre toda a cabeça.", t: { en: "helmet", es: "yelmo" } },
      "oiro": { def: "Variante portuguesa de 'ouro'. Metal precioso.", t: { en: "gold", es: "oro" } },
      "cetim": { def: "Tecido fino e brilhante de seda.", t: { en: "satin", es: "satén" } },
    },
  },

  /* ═══════════ ESPAÑOL ═══════════ */
  {
    id: "es-becquer",
    lang: "es",
    locale: "es-ES",
    author: "Gustavo Adolfo Bécquer",
    year: "1871",
    era: "romantic",
    title: "Rima LIII",
    subtitle: "Volverán las oscuras golondrinas…",
    blurb: "Rima de la pérdida y la singularidad del amor. Romanticismo tardío español.",
    stanzas: [
      [
        "Volverán las oscuras golondrinas",
        "en tu balcón sus nidos a colgar,",
        "y otra vez con el ala a sus cristales",
        "jugando llamarán;",
      ],
      [
        "pero aquellas que el vuelo refrenaban",
        "tu hermosura y mi dicha al contemplar,",
        "aquellas que aprendieron nuestros nombres…",
        "ésas… ¡no volverán!",
      ],
      [
        "Volverán las tupidas madreselvas",
        "de tu jardín las tapias a escalar,",
        "y otra vez a la tarde, aún más hermosas,",
        "sus flores se abrirán;",
      ],
      [
        "pero aquellas, cuajadas de rocío,",
        "cuyas gotas mirábamos temblar",
        "y caer, como lágrimas del día…",
        "ésas… ¡no volverán!",
      ],
    ],
    pronunciation: [
      { word: "golondrinas", hint: "go-lon-DRI-nas · ll suave", ipa: "ɡolonˈdɾinas" },
      { word: "balcón", hint: "bal-CÓN · acento agudo final", ipa: "balˈkon" },
      { word: "refrenaban", hint: "re-fre-NA-ban · rr inicial", ipa: "refɾeˈnaβan" },
      { word: "hermosura", hint: "er-mo-SU-ra · h muda", ipa: "eɾmoˈsuɾa" },
      { word: "dicha", hint: "DI-cha · ch como en 'mucho'", ipa: "ˈdit͡ʃa" },
      { word: "tupidas", hint: "tu-PI-das", ipa: "tuˈpiðas" },
      { word: "madreselvas", hint: "ma-dre-SEL-vas", ipa: "maðɾeˈselβas" },
      { word: "cuajadas", hint: "cua-JA-das · j gutural", ipa: "kwaˈxaðas" },
      { word: "rocío", hint: "ro-CÍ-o · acento en í", ipa: "roˈθio" },
    ],
    glossary: {
      "golondrinas": { def: "Aves migratórias de cauda forquilhada.", t: { en: "swallows", pt: "andorinhas" } },
      "balcón": { def: "Sacada, terraço elevado.", t: { en: "balcony", pt: "varanda" } },
      "nidos": { def: "Ninhos onde os pássaros chocam ovos.", t: { en: "nests", pt: "ninhos" } },
      "ala": { def: "Asa de ave.", t: { en: "wing", pt: "asa" } },
      "refrenaban": { def: "Detinham, freavam o voo.", t: { en: "they reined in", pt: "refreavam" } },
      "hermosura": { def: "Beleza, formosura.", t: { en: "beauty", pt: "formosura" } },
      "dicha": { def: "Felicidade, alegria.", t: { en: "bliss, happiness", pt: "ventura, felicidade" } },
      "tupidas": { def: "Densas, espessas.", t: { en: "thick, dense", pt: "espessas" } },
      "madreselvas": { def: "Plantas trepadeiras de flores perfumadas.", t: { en: "honeysuckle", pt: "madressilvas" } },
      "rocío": { def: "Orvalho, gotas matinais.", t: { en: "dew", pt: "orvalho" } },
    },
  },

  {
    id: "es-machado",
    lang: "es",
    locale: "es-ES",
    author: "Antonio Machado",
    year: "1912",
    era: "generation98",
    title: "Caminante, no hay camino",
    subtitle: "Proverbios y cantares · XXIX",
    blurb: "Da 'Campos de Castilla'. Sentença famosa sobre o caminho que se faz andando.",
    stanzas: [
      [
        "Caminante, son tus huellas",
        "el camino y nada más;",
        "Caminante, no hay camino,",
        "se hace camino al andar.",
      ],
      [
        "Al andar se hace el camino,",
        "y al volver la vista atrás",
        "se ve la senda que nunca",
        "se ha de volver a pisar.",
      ],
      [
        "Caminante no hay camino",
        "sino estelas en la mar.",
      ],
    ],
    pronunciation: [
      { word: "caminante", hint: "ca-mi-NAN-te", ipa: "kamiˈnante" },
      { word: "huellas", hint: "UE-llas · h muda · ll", ipa: "ˈweʎas" },
      { word: "camino", hint: "ca-MI-no", ipa: "kaˈmino" },
      { word: "andar", hint: "an-DAR", ipa: "anˈdaɾ" },
      { word: "volver", hint: "vol-VER · v como b", ipa: "bolˈβeɾ" },
      { word: "vista", hint: "BIS-ta", ipa: "ˈbista" },
      { word: "atrás", hint: "a-TRÁS · acento agudo", ipa: "aˈtɾas" },
      { word: "senda", hint: "SEN-da", ipa: "ˈsenda" },
      { word: "estelas", hint: "es-TE-las", ipa: "esˈtelas" },
    ],
    glossary: {
      "caminante": { def: "Andarilho, viajante a pé.", t: { en: "wanderer, walker", pt: "caminhante" } },
      "huellas": { def: "Marcas deixadas por pegadas.", t: { en: "footprints", pt: "pegadas" } },
      "camino": { def: "Senda, percurso.", t: { en: "path, road", pt: "caminho" } },
      "andar": { def: "Caminhar, locomover-se a pé.", t: { en: "to walk", pt: "andar, caminhar" } },
      "volver": { def: "Regressar, voltar.", t: { en: "to return", pt: "voltar" } },
      "vista": { def: "Olhar, ato de ver.", t: { en: "sight, view", pt: "vista" } },
      "atrás": { def: "Para trás, no passado.", t: { en: "back, behind", pt: "atrás" } },
      "senda": { def: "Vereda estreita, trilha.", t: { en: "path, trail", pt: "trilha" } },
      "pisar": { def: "Caminhar sobre, calcar com os pés.", t: { en: "to tread, step on", pt: "pisar" } },
      "estelas": { def: "Rastros que deixam os barcos no mar.", t: { en: "wakes (of ships)", pt: "esteiras (de barcos)" } },
    },
  },

  {
    id: "es-sorjuana",
    lang: "es",
    locale: "es-MX",
    author: "Sor Juana Inés de la Cruz",
    year: "1689",
    era: "goldenAge",
    title: "Hombres necios (excerto)",
    subtitle: "Hombres necios que acusáis a la mujer sin razón…",
    blurb: "Redondillas do Século de Ouro mexicano. Ironia feminista pioneira.",
    stanzas: [
      [
        "Hombres necios que acusáis",
        "a la mujer sin razón,",
        "sin ver que sois la ocasión",
        "de lo mismo que culpáis:",
      ],
      [
        "si con ansia sin igual",
        "solicitáis su desdén,",
        "¿por qué queréis que obren bien",
        "si las incitáis al mal?",
      ],
      [
        "Combatís su resistencia",
        "y luego, con gravedad,",
        "decís que fue liviandad",
        "lo que hizo la diligencia.",
      ],
      [
        "Parecer quiere el denuedo",
        "de vuestro parecer loco,",
        "al niño que pone el coco",
        "y luego le tiene miedo.",
      ],
    ],
    pronunciation: [
      { word: "necios", hint: "NE-cios · c suave", ipa: "ˈneθjos" },
      { word: "acusáis", hint: "a-cu-SÁIS · acento agudo", ipa: "akuˈsajs" },
      { word: "ocasión", hint: "o-ca-SIÓN", ipa: "okaˈsjon" },
      { word: "culpáis", hint: "cul-PÁIS", ipa: "kulˈpajs" },
      { word: "desdén", hint: "des-DÉN", ipa: "desˈðen" },
      { word: "obren", hint: "Ó-bren · rr suave", ipa: "ˈoβɾen" },
      { word: "liviandad", hint: "li-vian-DAD · v como b", ipa: "liβjanˈdað" },
      { word: "diligencia", hint: "di-li-GEN-cia · g gutural", ipa: "diliˈxenθja" },
      { word: "denuedo", hint: "de-NUE-do", ipa: "deˈnweðo" },
    ],
    glossary: {
      "necios": { def: "Tolos, ignorantes obstinados.", t: { en: "fools, foolish ones", pt: "néscios, tolos" } },
      "acusáis": { def: "Acusais. 2ª pessoa plural (vosotros) do indicativo.", t: { en: "you (pl.) accuse", pt: "vós acusais" } },
      "razón": { def: "Motivo justo; faculdade de raciocinar.", t: { en: "reason", pt: "razão" } },
      "ocasión": { def: "Causa, motivo que origina algo.", t: { en: "cause, occasion", pt: "ocasião, causa" } },
      "ansia": { def: "Desejo intenso, ânsia.", t: { en: "yearning, anxiety", pt: "ânsia" } },
      "desdén": { def: "Desprezo, indiferença orgulhosa.", t: { en: "disdain, scorn", pt: "desdém" } },
      "obren": { def: "Atuem, ajam. Subj. de 'obrar'.", t: { en: "(that they) act", pt: "ajam, obrem" } },
      "liviandad": { def: "Leviandade, falta de seriedade.", t: { en: "frivolity", pt: "leviandade" } },
      "denuedo": { def: "Ousadia, valentia.", t: { en: "daring, boldness", pt: "denodo, ousadia" } },
      "coco": { def: "Bicho-papão; figura assustadora infantil.", t: { en: "bogeyman", pt: "bicho-papão" } },
    },
  },

  {
    id: "es-lorca",
    lang: "es",
    locale: "es-ES",
    author: "Federico García Lorca",
    year: "1924",
    era: "generation27",
    title: "Canción del jinete",
    subtitle: "Córdoba. Lejana y sola.",
    blurb: "Da 'Canciones'. Ritmo de cavalgada e fatalidade. Andaluzia em vibração lírica.",
    stanzas: [
      [
        "Córdoba.",
        "Lejana y sola.",
      ],
      [
        "Jaca negra, luna grande,",
        "y aceitunas en mi alforja.",
        "Aunque sepa los caminos",
        "yo nunca llegaré a Córdoba.",
      ],
      [
        "Por el llano, por el viento,",
        "jaca negra, luna roja.",
        "La muerte me está mirando",
        "desde las torres de Córdoba.",
      ],
      [
        "¡Ay qué camino tan largo!",
        "¡Ay mi jaca valerosa!",
        "¡Ay que la muerte me espera,",
        "antes de llegar a Córdoba!",
      ],
      [
        "Córdoba.",
        "Lejana y sola.",
      ],
    ],
    pronunciation: [
      { word: "Córdoba", hint: "CÓR-do-ba", ipa: "ˈkoɾðoβa" },
      { word: "lejana", hint: "le-JA-na · j gutural", ipa: "leˈxana" },
      { word: "jaca", hint: "JA-ca · j gutural", ipa: "ˈxaka" },
      { word: "aceitunas", hint: "a-cei-TU-nas · c suave", ipa: "aθejˈtunas" },
      { word: "alforja", hint: "al-FOR-ja", ipa: "alˈfoɾxa" },
      { word: "aunque", hint: "AUN-que", ipa: "ˈawŋke" },
      { word: "caminos", hint: "ca-MI-nos", ipa: "kaˈminos" },
      { word: "llano", hint: "LLA-no · ll como y", ipa: "ˈʝano" },
      { word: "torres", hint: "TO-rres · rr forte", ipa: "ˈtores" },
    ],
    glossary: {
      "Córdoba": { def: "Cidade da Andaluzia, sul de Espanha.", t: { en: "Córdoba (city)", pt: "Córdoba (cidade)" } },
      "lejana": { def: "Distante, longínqua.", t: { en: "distant, far-away", pt: "longínqua, distante" } },
      "sola": { def: "Solitária, sem companhia.", t: { en: "alone, solitary", pt: "sozinha" } },
      "jaca": { def: "Égua pequena e vigorosa.", t: { en: "pony, small mare", pt: "égua pequena" } },
      "luna": { def: "Lua, satélite da Terra.", t: { en: "moon", pt: "lua" } },
      "aceitunas": { def: "Frutos da oliveira; azeitonas.", t: { en: "olives", pt: "azeitonas" } },
      "alforja": { def: "Bolsa dupla colocada sobre o lombo da besta.", t: { en: "saddlebag", pt: "alforje" } },
      "llano": { def: "Planície, terreno chato.", t: { en: "plain, flatland", pt: "planície" } },
      "muerte": { def: "Cessação da vida.", t: { en: "death", pt: "morte" } },
      "torres": { def: "Construções altas e estreitas.", t: { en: "towers", pt: "torres" } },
    },
  },
];

/* Helper: pre-process poems for word indexing */
function processPoem(poem) {
  const flat = [];
  let lineIdx = 0, wordIdx = 0;
  const lines = [];
  poem.stanzas.forEach((stanza, si) => {
    stanza.forEach((line) => {
      // Split into words while preserving punctuation
      const tokens = line.split(/(\s+)/).filter(t => t.length > 0);
      const words = [];
      tokens.forEach((tok) => {
        if (/^\s+$/.test(tok)) return;
        words.push({ raw: tok, clean: tok.replace(/[^\p{L}\p{N}'’-]/gu, "").toLowerCase(), wordIdx });
        flat.push({ raw: tok, clean: tok.replace(/[^\p{L}\p{N}'’-]/gu, "").toLowerCase(), lineIdx, stanzaIdx: si });
        wordIdx++;
      });
      lines.push({ raw: line, words, lineIdx, stanzaIdx: si, isFirstOfPoem: lineIdx === 0 });
      lineIdx++;
    });
  });
  return { ...poem, _lines: lines, _flatWords: flat };
}

const PROCESSED_POEMS = POEMS.map(processPoem);

Object.assign(window, { UI, ERAS, POEMS, PROCESSED_POEMS, processPoem });
